In [1]:
import numpy as np

In [25]:
dizi=[1,2,3,4,5]
dizi


[1, 2, 3, 4, 5]

In [3]:
np.array(dizi)

array([1, 2, 3, 4, 5])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
matrix=np.arange(3,30,3).reshape(3,3)
matrix2=np.arange(2,20,2).reshape(3,3)
arr=np.array([matrix,matrix2])
arr

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [19]:
np.random.seed(99)
random=np.random.randint(0, 100,6)
random


array([ 1, 35, 57, 40, 73, 82])

In [22]:
random.max()

82