In [1]:
import numpy as np

In [25]:
dizi=[1,2,3,4,5]
dizi


[1, 2, 3, 4, 5]

In [3]:
np.array(dizi)

array([1, 2, 3, 4, 5])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
matrix=np.arange(3,30,3).reshape(3,3)
matrix2=np.arange(2,20,2).reshape(3,3)
arr=np.array([matrix,matrix2])
arr

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [19]:
np.random.seed(99)
random=np.random.randint(0, 100,6)
random


array([ 1, 35, 57, 40, 73, 82])

In [22]:
random.max()

82

In [29]:
array1=np.linspace(14,88,22)
array1

array([14.        , 17.52380952, 21.04761905, 24.57142857, 28.0952381 ,
       31.61904762, 35.14285714, 38.66666667, 42.19047619, 45.71428571,
       49.23809524, 52.76190476, 56.28571429, 59.80952381, 63.33333333,
       66.85714286, 70.38095238, 73.9047619 , 77.42857143, 80.95238095,
       84.47619048, 88.        ])

In [30]:
array1.dtype

dtype('float64')

In [42]:
idx_arr=np.arange(0,10)
idx_arr=idx_arr.reshape(5,2)
idx_arr[3]


array([6, 7])

emre